name: pomodoro
description: "TM | Pomodoro - A simple Pomodoro timer app with a clean design."
publish_to: "tm.pomodoro"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  lucide_icons_flutter: ^3.1.0
  provider: ^6.1.5+1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: false
